
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://localhost:27017
      - MONGODB_DB_NAME=corebrain
      - REDIS_URL=redis://localhost:6379/0
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_MODEL=claude-3-opus-20240229
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    volumes:
      - ./app:/app/app
    networks:
      - corebrain-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - corebrain-network
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - corebrain-network
    restart: unless-stopped

  # Para entorno de desarrollo, incluir mongo-express
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - corebrain-network
    restart: unless-stopped
    profiles:
      - dev

networks:
  corebrain-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data: